// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iHelpU.MODEL.Models;

public partial class Status
{
    public int Id { get; set; }

    public string Descricao { get; set; }

    public virtual ICollection<AnuncioServico> AnuncioServicos { get; set; } = new List<AnuncioServico>();
}