// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iHelpU.MODEL.Models;

public partial class UsuarioCompetencium
{
    public int UsuarioId { get; set; }

    public string IdUsuarioCompetencia { get; set; }

    public int CompetenciaId { get; set; }

    public virtual Competencia Competencia { get; set; }

    public virtual Usuario Usuario { get; set; }
}